Repository GEnacheC/MakitasMod, pull requests merged in 2025-10, with the labels that each got.

#2 HOTFIX- Makitas Drops fixed
  gradle.properties
  src/main/java/net/genachec/makitasmod/ClientSetup.java
  src/main/java/net/genachec/makitasmod/MakitasMod.java
  src/main/java/net/genachec/makitasmod/abstracts/MakitasModObject.java
  src/main/java/net/genachec/makitasmod/block/MakitasModBlocks.java
  src/main/java/net/genachec/makitasmod/interfaces/MakitasModBaseInterface.java
  src/main/java/net/genachec/makitasmod/interfaces/MakitasModBlockInterface.java
  src/main/java/net/genachec/makitasmod/interfaces/MakitasModItemsInterface.java
  src/main/java/net/genachec/makitasmod/item/MakitasModCreativeTabs.java
  src/main/java/net/genachec/makitasmod/item/MakitasModItems.java
  src/main/resources/data/makitasmod/loot_tables/blocks/makitas_block.json
  src/main/resources/data/minecraft/tags/blocks/mineable/axe.json
  src/main/resources/data/minecraft/tags/blocks/mineable/hoe.json
  src/main/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/resources/data/minecraft/tags/blocks/mineable/shovel.json
  src/main/resources/data/minecraft/tags/blocks/needs_iron_tool.json
Labels: bug

#3 Dev
  gradle.properties
  src/main/java/net/genachec/makitasmod/ClientSetup.java
  src/main/java/net/genachec/makitasmod/MakitasMod.java
  src/main/java/net/genachec/makitasmod/abstracts/MakitasModObject.java
  src/main/java/net/genachec/makitasmod/block/MakitasModBlocks.java
  src/main/java/net/genachec/makitasmod/interfaces/MakitasModBaseInterface.java
  src/main/java/net/genachec/makitasmod/interfaces/MakitasModBlockInterface.java
  src/main/java/net/genachec/makitasmod/interfaces/MakitasModItemsInterface.java
  src/main/java/net/genachec/makitasmod/item/MakitasModCreativeTabs.java
  src/main/java/net/genachec/makitasmod/item/MakitasModItems.java
  src/main/resources/data/makitasmod/loot_tables/blocks/makitas_block.json
  src/main/resources/data/minecraft/tags/blocks/mineable/axe.json
  src/main/resources/data/minecraft/tags/blocks/mineable/hoe.json
  src/main/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/resources/data/minecraft/tags/blocks/mineable/shovel.json
  src/main/resources/data/minecraft/tags/blocks/needs_iron_tool.json
Labels: 1.0.1

#7 Update to Version 1.2.0
  gradle.properties
  src/main/java/net/genachec/makitasmod/block/MakitasModBlocks.java
  src/main/java/net/genachec/makitasmod/block/custom/MakitaBlock.java
  src/main/resources/assets/makitasmod/blockstates/makitas_block.json
  src/main/resources/assets/makitasmod/blockstates/makitas_diamond_makita_block.json
  src/main/resources/assets/makitasmod/blockstates/makitas_end_makita_block.json
  src/main/resources/assets/makitasmod/blockstates/makitas_gold_makita_block.json
  src/main/resources/assets/makitasmod/blockstates/makitas_iron_makita_block.json
  src/main/resources/assets/makitasmod/lang/en_us.json
  src/main/resources/assets/makitasmod/lang/pt_br.json
  src/main/resources/assets/makitasmod/models/block/makitas_diamond_makita_block.json
  src/main/resources/assets/makitasmod/models/block/makitas_end_makita_block.json
  src/main/resources/assets/makitasmod/models/block/makitas_gold_makita_block.json
  src/main/resources/assets/makitasmod/models/block/makitas_iron_makita_block.json
  src/main/resources/assets/makitasmod/models/item/makitas_block.json
  src/main/resources/assets/makitasmod/models/item/makitas_diamond_makita_block.json
  src/main/resources/assets/makitasmod/models/item/makitas_end_makita_block.json
  src/main/resources/assets/makitasmod/models/item/makitas_gold_makita_block.json
  src/main/resources/assets/makitasmod/models/item/makitas_iron_makita_block.json
  src/main/resources/assets/makitasmod/models/obj/makitas_block.obj
  src/main/resources/assets/makitasmod/textures/block/legacy_diamond_block.png
  src/main/resources/assets/makitasmod/textures/block/legacy_gold_block.png
  src/main/resources/data/makitasmod/loot_tables/blocks/makitas_diamond_makita_block.json
  src/main/resources/data/makitasmod/loot_tables/blocks/makitas_end_makita_block.json
  src/main/resources/data/makitasmod/loot_tables/blocks/makitas_gold_makita_block.json
  src/main/resources/data/makitasmod/loot_tables/blocks/makitas_iron_makita_block.json
  src/main/resources/data/makitasmod/recipes/makitas_diamond_makita_block.json
  src/main/resources/data/makitasmod/recipes/makitas_end_makita_block.json
  src/main/resources/data/makitasmod/recipes/makitas_gold_makita_block.json
  src/main/resources/data/makitasmod/recipes/makitas_iron_makita_block.json
  src/main/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/resources/data/minecraft/tags/blocks/needs_iron_tool.json
Labels: 1.2.0
